site:
    baseUrl: "https://stewartlynch.github.io/CreaTECHSolutions/"
    title: "CreaTECH Solutions"
    navigation:
        - label: "Home"
          url: "/"
        - label: "Eh!"
          url: "/about/"
