site:
    baseUrl: "https://stewartlynch.github.io/CreaTECHSolutions/"
    title: "CreaTECH Solutions"
    navigation:
        - label: "Home"
          url: "/CreaTECHSolutions"
        - label: "About"
          url: "/CreaTECHSolutions/about/"
